// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5durAAa9kkoqlPoPshsDT6QGj6vb4LK8',
    appId: '1:473638062019:web:19e69769ecf75fcd4c1f76',
    messagingSenderId: '473638062019',
    projectId: 'powerwise00',
    authDomain: 'powerwise00.firebaseapp.com',
    databaseURL: 'https://powerwise00-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'powerwise00.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA31Jxretax4diOiDKizzVU-ck5Df5jf3g',
    appId: '1:473638062019:android:575c9a31e93a936d4c1f76',
    messagingSenderId: '473638062019',
    projectId: 'powerwise00',
    databaseURL: 'https://powerwise00-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'powerwise00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVRkEGfCyGM2zfuUcKJkx0FoPtOvE0hWI',
    appId: '1:473638062019:ios:891cff95fcc694cb4c1f76',
    messagingSenderId: '473638062019',
    projectId: 'powerwise00',
    databaseURL: 'https://powerwise00-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'powerwise00.appspot.com',
    iosBundleId: 'com.example.powerWise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVRkEGfCyGM2zfuUcKJkx0FoPtOvE0hWI',
    appId: '1:473638062019:ios:10311c90f8a484124c1f76',
    messagingSenderId: '473638062019',
    projectId: 'powerwise00',
    databaseURL: 'https://powerwise00-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'powerwise00.appspot.com',
    iosBundleId: 'com.example.powerWise.RunnerTests',
  );
}
